"""Paths, variable sets and physical bounds."""

from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DATA = REPO / "data" / "ecland_cy49r2_2020_2022.zarr"
MODELS = REPO / "models"
FIGURES = REPO / "figures"

SEED = 42

#: Static / climatological descriptors. Inputs only.
STATIC = [
    "clim_CLAKE",
    "clim_Ctype",
    "clim_cu",
    "clim_cvh",
    "clim_cvl",
    "clim_geopot",
    "clim_sdfor",
    "clim_sdor",
    "clim_sotype",
    "clim_tvh",
    "clim_tvl",
    "clim_z0m",
    "lai_hv",
    "lai_lv",
]

#: Meteorological forcing. Inputs only.
MET = [
    "met_ctpf",
    "met_lwdown",
    "met_psurf",
    "met_qair",
    "met_rainf",
    "met_swdown",
    "met_snowf",
    "met_tair",
    "met_wind_e",
    "met_wind_n",
]

#: Temporal / astronomical forcing, derived from the time coordinate and the
#: point's longitude rather than read from the store. aiLand v1 adds these to the
#: input space and reports they specifically improve soil temperature; the anemoi
#: stores on /lus carry them precomputed under exactly these names.
TEMPORAL = [
    "cos_julian_day",
    "sin_julian_day",
    "cos_local_time",
    "sin_local_time",
    "insolation",
]

#: Static geographic encodings. v1 includes these, but with only 10 points in the
#: mock store they act as point identifiers, so they are off by default here.
GEO = ["cos_latitude", "sin_latitude", "cos_longitude", "sin_longitude"]

#: Variable-set presets: (prognostic, diagnostic).
#:
#: Prognostic variables are predicted as 6-hourly increments, added to the
#: previous state and fed back into the input vector at the next step.
#: Diagnostic variables are predicted as absolute values, re-diagnosed from the
#: prognostic state at every step, and never fed back -- feeding them back from
#: the truth data would leak information into the rollout.
PRESETS = {
    # v0's soil and snow state. The notebook as distributed also carried sro/ssro
    # here, but runoff is a flux generated by the column rather than a state of
    # it, so the fair statement of the v0 design is these seven variables.
    "v0": (
        ["swvl1", "swvl2", "swvl3", "stl1", "stl2", "stl3", "snowc"],
        [],
    ),
    # v0 exactly as distributed, runoff included in the state. Kept only so the
    # original notebook remains runnable and reproducible.
    "v0-asdistributed": (
        ["swvl1", "swvl2", "swvl3", "stl1", "stl2", "stl3", "snowc", "sro", "ssro"],
        [],
    ),
    # v0 plus the snow prognostics and two diagnostics already in the store.
    "v0+snow": (
        ["swvl1", "swvl2", "swvl3", "stl1", "stl2", "stl3", "snowc", "sd", "rsn",
         "sro", "ssro"],
        ["skt", "aco2gpp"],
    ),
    # The aiLand v1 state vector (Raoult et al. 2026, Table 1): only soil
    # temperature/moisture and snow cover are prognostic. Note that v1 promotes
    # snowc to prognostic although it is diagnostic in ecLand, and drops runoff.
    "v1": (
        ["swvl1", "swvl2", "swvl3", "stl1", "stl2", "stl3", "snowc"],
        ["skt", "aco2gpp"],
    ),
    # v1's state vector, with runoff recovered as DIAGNOSTIC output rather than
    # dropped. Qs/Qsb (GRIB sro/ssro) are fluxes generated by the soil column, not
    # states of it: they are predicted from the current state each step and never
    # fed back, so they cannot contaminate the prognostic rollout the way they do
    # in the v0 preset.
    "v1+runoff": (
        ["swvl1", "swvl2", "swvl3", "stl1", "stl2", "stl3", "snowc"],
        ["skt", "aco2gpp", "sro", "ssro"],
    ),
}

DEFAULT_PRESET = "v0+snow"

# ---------------------------------------------------------------------------
# O96 profile: the real aiLand v1 training data, extracted from the anemoi store
# on /lus by ailand.extract. Different variable names, and it carries everything
# the mock store lacks -- evaporation, the turbulent fluxes, 2t/2d -- as well as
# the temporal forcings already precomputed.
# ---------------------------------------------------------------------------

O96_STATIC = [
    "cl", "dl", "cvh_0", "cvl_0", "tvh_0", "tvl_0", "hveg_cov_0", "lveg_cov_0",
    "hveg_rsmin_0", "lveg_rsmin_0", "hveg_z0m_0", "lveg_z0m_0",
    "theta_cap_0", "theta_pwp_0", "sdor_0", "isor_0", "anor_0", "slor_0",
    "z", "lsm_0", "c3_c4_0",
]

O96_MET = [
    "t_ml_137", "q_ml_137", "u_ml_137", "v_ml_137",
    "ssrd", "strd", "tp", "sf", "sp", "lai_hv", "lai_lv",
]

#: Already present in the store, so nothing is derived for this profile.
O96_TEMPORAL = [
    "cos_julian_day", "sin_julian_day", "cos_local_time", "sin_local_time",
    "insolation",
]
O96_GEO = ["cos_latitude", "sin_latitude", "cos_longitude", "sin_longitude"]

O96_PRESETS = {
    # Exactly aiLand v1, Table 1: 7 prognostic states, 5 diagnostic outputs.
    "v1": (
        ["stl1", "stl2", "stl3", "swvl1", "swvl2", "swvl3", "snowc"],
        ["2t", "2d", "skt", "slhf", "sshf"],
    ),
    # v1 plus the fluxes v1 does not output: evaporation, runoff and GPP.
    # All are diagnostics -- fluxes generated by the column, not states of it.
    "v1+fluxes": (
        ["stl1", "stl2", "stl3", "swvl1", "swvl2", "swvl3", "snowc"],
        ["2t", "2d", "skt", "slhf", "sshf", "e", "sro", "ssro", "aco2gpp"],
    ),
}

O96_BOUNDS = {
    "swvl1": (0.0, 1.0),
    "swvl2": (0.0, 1.0),
    "swvl3": (0.0, 1.0),
    "stl1": (None, None),
    "stl2": (None, None),
    "stl3": (None, None),
    "snowc": (0.0, 1.0),
}

#: Diagnostic bounds for the O96 profile. Note evaporation is NOT bounded below:
#: ECMWF sign convention is downward-positive, so evaporation is negative and
#: condensation/dew is positive.
O96_DIAG_BOUNDS = {
    "sro": (0.0, None),
    "ssro": (0.0, None),
    "aco2gpp": (0.0, None),
}

#: Physical bounds applied to prognostic states after each update, as v1 does in
#: post-processing. ``None`` means unbounded on that side.
#:
#: NOTE: snowc is a PERCENTAGE in this store (0-99.9), not a fraction. The v0
#: notebook's "Snow Cover Fraction (-)" label is wrong and a [0, 1] bound on it
#: destroys the signal entirely.
BOUNDS = {
    "swvl1": (0.0, None),
    "swvl2": (0.0, None),
    "swvl3": (0.0, None),
    "stl1": (None, None),
    "stl2": (None, None),
    "stl3": (None, None),
    "snowc": (0.0, 100.0),
    "sd": (0.0, None),
    "rsn": (50.0, 450.0),
    "sro": (0.0, None),
    "ssro": (0.0, None),
}

#: Bounds applied to diagnostic outputs too. Runoff and GPP are non-negative by
#: construction; skin temperature is unbounded.
DIAG_BOUNDS = {
    "sro": (0.0, None),
    "ssro": (0.0, None),
    "aco2gpp": (0.0, None),
}

UNITS = {
    "swvl1": "Soil Moisture (m3 m-3)",
    "swvl2": "Soil Moisture (m3 m-3)",
    "swvl3": "Soil Moisture (m3 m-3)",
    "stl1": "Soil Temperature (K)",
    "stl2": "Soil Temperature (K)",
    "stl3": "Soil Temperature (K)",
    "snowc": "Snow Cover (%)",
    "sd": "Snow Depth (m water eq.)",
    "rsn": "Snow Density (kg m-3)",
    "sro": "Surface Runoff (m)",
    "ssro": "Subsurface Runoff (m)",
    "skt": "Skin Temperature (K)",
    "aco2gpp": "GPP (kg m-2 s-1)",
}


#: Dataset profiles: which variable names and presets apply to a given store.
PROFILES = {
    "mock": dict(static=None, met=None, temporal=None, geo=None,
                 presets=None, bounds=None, diag_bounds=None, derive_temporal=True),
    "o96": dict(static=O96_STATIC, met=O96_MET, temporal=O96_TEMPORAL, geo=O96_GEO,
                presets=O96_PRESETS, bounds=O96_BOUNDS, diag_bounds=O96_DIAG_BOUNDS,
                derive_temporal=False),
}


def profile(name="mock"):
    """Resolve a dataset profile, filling the ``mock`` defaults."""
    if name not in PROFILES:
        raise KeyError(f"unknown profile {name!r}; choose from {sorted(PROFILES)}")
    p = dict(PROFILES[name])
    p["static"] = p["static"] or STATIC
    p["met"] = p["met"] or MET
    p["temporal"] = p["temporal"] or TEMPORAL
    p["geo"] = p["geo"] or GEO
    p["presets"] = p["presets"] or PRESETS
    p["bounds"] = p["bounds"] or BOUNDS
    p["diag_bounds"] = p["diag_bounds"] or DIAG_BOUNDS
    return p


def features(prognostic, temporal=False, geo=False, prof="mock"):
    """Input vector: statics + forcing + previous prognostic state.

    :param temporal: append the temporal/astronomical forcing of :data:`TEMPORAL`
    :param geo: append the static geographic encodings of :data:`GEO`
    """
    p = profile(prof)
    feat = list(p["static"]) + list(p["met"])
    if temporal:
        feat += list(p["temporal"])
    if geo:
        feat += list(p["geo"])
    return feat + list(prognostic)


def resolve(preset, temporal=False, geo=False, prof="mock"):
    """Return ``(prognostic, diagnostic, features)`` for a named preset."""
    p = profile(prof)
    if preset not in p["presets"]:
        raise KeyError(f"unknown preset {preset!r} for profile {prof!r}; "
                       f"choose from {sorted(p['presets'])}")
    prog, diag = p["presets"][preset]
    return list(prog), list(diag), features(prog, temporal=temporal, geo=geo, prof=prof)
